# Generated by Django 5.2.4 on 2025-09-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_gasto_user_ingreso_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='concepto',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='concepto',
            field=models.CharField(max_length=300),
        ),
    ]
